const structure = {
  //校內幹部經歷
  幹部經歷: [
    { label: '單位名稱', width: '', prop: '單位名稱', hidden: 'N', sort: 1, defult: '' },
    { label: '幹部等級', width: '', prop: '幹部等級', hidden: 'N', sort: 2, defult: '' },
    { label: '擔任職務', width: '', prop: '擔任職務', hidden: 'N', sort: 3, defult: '' },
    { label: '開始日期', width: '', prop: '開始日期', hidden: 'N', sort: 4, defult: '' },
    { label: '結束日期', width: '', prop: '結束日期', hidden: 'N', sort: 5, defult: '' },
  ],
  //多元表現
  幹部經歷暨事蹟紀錄: [
    { label: '單位名稱', width: '', prop: '單位名稱', hidden: 'N', sort: 1, defult: '' },
    { label: '開始日期', width: '', prop: '開始日期', hidden: 'N', sort: 2, defult: '' },
    { label: '結束日期', width: '', prop: '結束日期', hidden: 'N', sort: 3, defult: '' },
    { label: '擔任職務', width: '', prop: '擔任職務', hidden: 'N', sort: 4, defult: '' },
    { label: '幹部等級', width: '', prop: '幹部等級', hidden: 'N', sort: 5, defult: '' },
    { label: '內容簡述', width: '', prop: '內容簡述', hidden: 'N', sort: 6, defult: '' },
    { label: '影音檔案外部連結', width: '', prop: '影音檔案外部連結', hidden: 'N', sort: 7, defult: '' },
  ],
  競賽參與紀錄: [
    { label: '競賽名稱', width: '', prop: '競賽名稱', hidden: 'N', sort: 1, defult: '' },
    { label: '項目', width: '', prop: '項目', hidden: 'N', sort: 2, defult: '' },
    { label: '競賽等級', width: '', prop: '競賽等級', hidden: 'N', sort: 3, defult: '' },
    { label: '獎項', width: '', prop: '獎項', hidden: 'N', sort: 4, defult: '' },
    { label: '結果公布日期', width: '', prop: '結果公布日期', hidden: 'N', sort: 5, defult: '' },
    { label: '團體參與', width: '', prop: '團體參與', hidden: 'N', sort: 6, defult: '' },
    { label: '內容簡述', width: '', prop: '內容簡述', hidden: 'N', sort: 7, defult: '' },
    { label: '影音檔案外部連結', width: '', prop: '影音檔案外部連結', hidden: 'N', sort: 8, defult: '' },
  ],
  檢定證照紀錄: [
    { label: '證照代碼', width: '', prop: '證照代碼', hidden: 'N', sort: 1, defult: '' },
    { label: '檢定證照類別', width: '', prop: '檢定證照類別', hidden: 'N', sort: 2, defult: '' },
    { label: '國內國外', width: '', prop: '國內國外', hidden: 'N', sort: 3, defult: '' },
    { label: '證照類別', width: '', prop: '證照類別', hidden: 'N', sort: 4, defult: '' },
    { label: '發照單位', width: '', prop: '發照單位', hidden: 'N', sort: 5, defult: '' },
    { label: '證照名稱', width: '', prop: '證照名稱', hidden: 'N', sort: 6, defult: '' },
    { label: '級數分數', width: '', prop: '級數分數', hidden: 'N', sort: 7, defult: '' },
    { label: '分數', width: '', prop: '分數', hidden: 'N', sort: 8, defult: '' },
    { label: '分項結果', width: '', prop: '分項結果', hidden: 'N', sort: 9, defult: '' },
    { label: '取得證照日期', width: '', prop: '取得證照日期', hidden: 'N', sort: 10, defult: '' },
    { label: '證照字號', width: '', prop: '證照字號', hidden: 'N', sort: 11, defult: '' },
    { label: '檢定組別', width: '', prop: '檢定組別', hidden: 'N', sort: 12, defult: '' },
    { label: '內容簡述', width: '', prop: '內容簡述', hidden: 'N', sort: 13, defult: '' },
    { label: '影音檔案外部連結', width: '', prop: '影音檔案外部連結', hidden: 'N', sort: 14, defult: '' },
  ],
  服務學習紀錄: [
    { label: '服務名稱', width: '', prop: '服務名稱', hidden: 'N', sort: 1, defult: '' },
    { label: '服務單位', width: '', prop: '服務單位', hidden: 'N', sort: 2, defult: '' },
    { label: '開始日期', width: '', prop: '開始日期', hidden: 'N', sort: 3, defult: '' },
    { label: '結束日期', width: '', prop: '結束日期', hidden: 'N', sort: 4, defult: '' },
    { label: '時數', width: '', prop: '時數', hidden: 'N', sort: 5, defult: '' },
    { label: '內容簡述', width: '', prop: '內容簡述', hidden: 'N', sort: 6, defult: '' },
    { label: '影音檔案外部連結', width: '', prop: '影音檔案外部連結', hidden: 'N', sort: 7, defult: '' },
  ],
  彈性學習時間紀錄: [
    { label: '彈性學習時間類別(種類)', width: '', prop: '彈性學習時間類別(種類)', hidden: 'N', sort: 1, defult: '' },
    { label: '內容(開設名稱)', width: '', prop: '內容(開設名稱)', hidden: 'N', sort: 2, defult: '' },
    { label: '開設單位', width: '', prop: '開設單位', hidden: 'N', sort: 3, defult: '' },
    { label: '開設學年度', width: '', prop: '開設學年度', hidden: 'N', sort: 4, defult: '' },
    { label: '開設學期', width: '', prop: '開設學期', hidden: 'N', sort: 5, defult: '' },
    { label: '每週節數', width: '', prop: '每週節數', hidden: 'N', sort: 6, defult: '' },
    { label: '開設週數', width: '', prop: '開設週數', hidden: 'N', sort: 7, defult: '' },
    { label: '內容簡述', width: '', prop: '內容簡述', hidden: 'N', sort: 8, defult: '' },
    { label: '影音檔案外部連結', width: '', prop: '影音檔案外部連結', hidden: 'N', sort: 9, defult: '' },
  ],
  團體活動時間紀錄: [
    { label: '團體活動時間類別', width: '', prop: '團體活動時間類別', hidden: 'N', sort: 1, defult: '' },
    { label: '辦理單位', width: '', prop: '辦理單位', hidden: 'N', sort: 2, defult: '' },
    { label: '團體活動內容名稱', width: '', prop: '團體活動內容名稱', hidden: 'N', sort: 3, defult: '' },
    { label: '活動學年度', width: '', prop: '活動學年度', hidden: 'N', sort: 4, defult: '' },
    { label: '活動學期', width: '', prop: '活動學期', hidden: 'N', sort: 5, defult: '' },
    { label: '節數', width: '', prop: '節數', hidden: 'N', sort: 6, defult: '' },
    { label: '內容簡述', width: '', prop: '內容簡述', hidden: 'N', sort: 7, defult: '' },
    { label: '影音檔案外部連結', width: '', prop: '影音檔案外部連結', hidden: 'N', sort: 8, defult: '' },
  ],
  職場學習紀錄: [
    { label: '職場學習類別', width: '', prop: '職場學習類別', hidden: 'N', sort: 1, defult: '' },
    { label: '職場學習單位', width: '', prop: '職場學習單位', hidden: 'N', sort: 2, defult: '' },
    { label: '職場學習職稱', width: '', prop: '職場學習職稱', hidden: 'N', sort: 3, defult: '' },
    { label: '開始日期', width: '', prop: '開始日期', hidden: 'N', sort: 4, defult: '' },
    { label: '結束日期', width: '', prop: '結束日期', hidden: 'N', sort: 5, defult: '' },
    { label: '時數', width: '', prop: '時數', hidden: 'N', sort: 6, defult: '' },
    { label: '內容簡述', width: '', prop: '內容簡述', hidden: 'N', sort: 7, defult: '' },
    { label: '影音檔案外部連結', width: '', prop: '影音檔案外部連結', hidden: 'N', sort: 8, defult: '' },
  ],
  作品成果紀錄: [
    { label: '名稱', width: '', prop: '名稱', hidden: 'N', sort: 1, defult: '' },
    { label: '日期', width: '', prop: '日期', hidden: 'N', sort: 2, defult: '' },
    { label: '內容簡述', width: '', prop: '內容簡述', hidden: 'N', sort: 3, defult: '' },
    { label: '影音檔案外部連結', width: '', prop: '影音檔案外部連結', hidden: 'N', sort: 4, defult: '' },
  ],
  大學及技專校院先修課程紀錄: [
    { label: '開設單位', width: '', prop: '開設單位', hidden: 'N', sort: 1, defult: '' },
    { label: '開設單位', width: '', prop: '開設單位', hidden: 'N', sort: 2, defult: '' },
    { label: '課程名稱', width: '', prop: '課程名稱', hidden: 'N', sort: 3, defult: '' },
    { label: '開始日期', width: '', prop: '開始日期', hidden: 'N', sort: 4, defult: '' },
    { label: '結束日期', width: '', prop: '結束日期', hidden: 'N', sort: 5, defult: '' },
    { label: '學分數', width: '', prop: '學分數', hidden: 'N', sort: 6, defult: '' },
    { label: '總時數', width: '', prop: '總時數', hidden: 'N', sort: 7, defult: '' },
    { label: '內容簡述', width: '', prop: '內容簡述', hidden: 'N', sort:8, defult: '' },
    { label: '影音檔案外部連結', width: '', prop: '影音檔案外部連結', hidden: 'N', sort: 9, defult: '' },
  ],
  其他多元表現紀錄: [
    { label: '名稱', width: '', prop: '名稱', hidden: 'N', sort: 1, defult: '' },
    { label: '主辦單位', width: '', prop: '主辦單位', hidden: 'N', sort: 2, defult: '' },
    { label: '開始日期', width: '', prop: '開始日期', hidden: 'N', sort: 3, defult: '' },
    { label: '結束日期', width: '', prop: '結束日期', hidden: 'N', sort: 4, defult: '' },
    { label: '時數', width: '', prop: '時數', hidden: 'N', sort: 5, defult: '' },
    { label: '內容簡述', width: '', prop: '內容簡述', hidden: 'N', sort: 6, defult: '' },
    { label: '影音檔案外部連結', width: '', prop: '影音檔案外部連結', hidden: 'N', sort: 7, defult: '' },
  ],
  //課程學習成果
  學期課程學習成果: [
    { label: '開課年級', width: '', prop: '開課年級', hidden: 'N', sort: 1, defult: '' },
    { label: '課程代碼', width: '', prop: '課程代碼', hidden: 'N', sort: 2, defult: '' },
    { label: '科目名稱', width: '', prop: '科目名稱', hidden: 'N', sort: 3, defult: '' },
    { label: '修課學分', width: '', prop: '修課學分', hidden: 'N', sort: 4, defult: '' },
    { label: '實際修課學年度', width: '', prop: '實際修課學年度', hidden: 'N', sort: 5, defult: '' },
    { label: '實際修課學期', width: '', prop: '實際修課學期', hidden: 'N', sort: 6, defult: '' },
    { label: '成果簡述', width: '', prop: '成果簡述', hidden: 'N', sort: 7, defult: '' },
  ],
  補修課程學習成果: [
    { label: '應修課學年度', width: '', prop: '應修課學年度', hidden: 'N', sort: 1, defult: '' },
    { label: '應修課學期', width: '', prop: '應修課學期', hidden: 'N', sort: 2, defult: '' },
    { label: '課程代碼', width: '', prop: '課程代碼', hidden: 'N', sort: 3, defult: '' },
    { label: '科目名稱', width: '', prop: '科目名稱', hidden: 'N', sort: 4, defult: '' },
    { label: '開課年級', width: '', prop: '開課年級', hidden: 'N', sort: 5, defult: '' },
    { label: '修課學分', width: '', prop: '修課學分', hidden: 'N', sort: 6, defult: '' },
    { label: '實際修課學年度', width: '', prop: '實際修課學年度', hidden: 'N', sort: 7, defult: '' },
    { label: '實際修課學期', width: '', prop: '實際修課學期', hidden: 'N', sort: 8, defult: '' },
    { label: '成果簡述', width: '', prop: '成果簡述', hidden: 'N', sort: 9, defult: '' },
  ],
  重修課程學習成果: [
    { label: '原修課學年度', width: '', prop: '原修課學年度', hidden: 'N', sort: 1, defult: '' },
    { label: '原修課學期', width: '', prop: '原修課學期', hidden: 'N', sort: 2, defult: '' },
    { label: '原修課課程代碼', width: '', prop: '原修課課程代碼', hidden: 'N', sort: 3, defult: '' },
    { label: '原修課科目名稱', width: '', prop: '原修課科目名稱', hidden: 'N', sort: 4, defult: '' },
    { label: '原修課開課年級', width: '', prop: '原修課開課年級', hidden: 'N', sort: 5, defult: '' },
    { label: '原修課修課學分', width: '', prop: '原修課修課學分', hidden: 'N', sort: 6, defult: '' },
    { label: '實際修課學年度', width: '', prop: '實際修課學年度', hidden: 'N', sort: 7, defult: '' },
    { label: '實際修課學期', width: '', prop: '實際修課學期', hidden: 'N', sort: 8, defult: '' },
    { label: '成果簡述', width: '', prop: '成果簡述', hidden: 'N', sort: 9, defult: '' },
  ],
  重讀課程學習成果: [
    { label: '開課年級', width: '', prop: '開課年級', hidden: 'N', sort: 1, defult: '' },
    { label: '課程代碼', width: '', prop: '課程代碼', hidden: 'N', sort: 2, defult: '' },
    { label: '科目名稱', width: '', prop: '科目名稱', hidden: 'N', sort: 3, defult: '' },
    { label: '修課學分', width: '', prop: '修課學分', hidden: 'N', sort: 4, defult: '' },
    { label: '實際修課學年度', width: '', prop: '實際修課學年度', hidden: 'N', sort: 5, defult: '' },
    { label: '實際修課學期', width: '', prop: '實際修課學期', hidden: 'N', sort: 6, defult: '' },
    { label: '成果簡述', width: '', prop: '成果簡述', hidden: 'N', sort: 7, defult: '' },
  ],
  轉學轉科課程學習成果: [
    { label: '原修課學校名稱', width: '', prop: '原修課學校名稱', hidden: 'N', sort: 1, defult: '' },
    { label: '原修課學年度', width: '', prop: '原修課學年度', hidden: 'N', sort: 2, defult: '' },
    { label: '原修課學期', width: '', prop: '原修課學期', hidden: 'N', sort: 3, defult: '' },
    { label: '原修課課程代碼', width: '', prop: '原修課課程代碼', hidden: 'N', sort: 4, defult: '' },
    { label: '原修課科目名稱', width: '', prop: '原修課科目名稱', hidden: 'N', sort: 5, defult: '' },
    { label: '原修課開課年級', width: '', prop: '原修課開課年級', hidden: 'N', sort: 6, defult: '' },
    { label: '原修課修課學分', width: '', prop: '原修課修課學分', hidden: 'N', sort: 7, defult: '' },
    { label: '成果簡述', width: '', prop: '成果簡述', hidden: 'N', sort: 8, defult: '' },
  ],
  借讀課程學習成果: [
    { label: '借讀學校名稱', width: '', prop: '借讀學校名稱', hidden: 'N', sort: 1, defult: '' },
    { label: '借讀修課學年度', width: '', prop: '借讀修課學年度', hidden: 'N', sort: 2, defult: '' },
    { label: '借讀修課學期', width: '', prop: '借讀修課學期', hidden: 'N', sort: 2, defult: '' },
    { label: '借讀校課程代碼', width: '', prop: '借讀校課程代碼', hidden: 'N', sort: 3, defult: '' },
    { label: '借讀校科目名稱', width: '', prop: '借讀校科目名稱', hidden: 'N', sort: 4, defult: '' },
    { label: '借讀校開課年級', width: '', prop: '借讀校開課年級', hidden: 'N', sort: 5, defult: '' },
    { label: '借讀校修課學分', width: '', prop: '借讀校修課學分', hidden: 'N', sort: 6, defult: '' },
    { label: '成果簡述', width: '', prop: '成果簡述', hidden: 'N', sort: 7, defult: '' },
  ],
  進修部學期課程學習成果: [
    { label: '開課年級', width: '', prop: '開課年級', hidden: 'N', sort: 1, defult: '' },
    { label: '課程代碼', width: '', prop: '課程代碼', hidden: 'N', sort: 2, defult: '' },
    { label: '科目名稱', width: '', prop: '科目名稱', hidden: 'N', sort: 3, defult: '' },
    { label: '修課節數', width: '', prop: '修課節數', hidden: 'N', sort: 4, defult: '' },
    { label: '實際修課學年度', width: '', prop: '實際修課學年度', hidden: 'N', sort: 5, defult: '' },
    { label: '實際修課學期', width: '', prop: '實際修課學期', hidden: 'N', sort: 6, defult: '' },
    { label: '成果簡述', width: '', prop: '成果簡述', hidden: 'N', sort: 7, defult: '' },
  ],
  進修部轉學: [
    { label: '原修課學校名稱', width: '', prop: '原修課學校名稱', hidden: 'N', sort: 1, defult: '' },
    { label: '原修課學年度', width: '', prop: '原修課學年度', hidden: 'N', sort: 2, defult: '' },
    { label: '原修課學期', width: '', prop: '原修課學期', hidden: 'N', sort: 3, defult: '' },
    { label: '原修課課程代碼', width: '', prop: '原修課課程代碼', hidden: 'N', sort: 4, defult: '' },
    { label: '原修課科目名稱', width: '', prop: '原修課科目名稱', hidden: 'N', sort: 5, defult: '' },
    { label: '原修課開課年級', width: '', prop: '原修課開課年級', hidden: 'N', sort: 6, defult: '' },
    { label: '原修課修課節數', width: '', prop: '原修課修課節數', hidden: 'N', sort: 7, defult: '' },
    { label: '成果簡述', width: '', prop: '成果簡述', hidden: 'N', sort: 8, defult: '' },
  ],
  進修部借讀課程學習成果: [
    { label: '借讀學校名稱', width: '', prop: '借讀學校名稱', hidden: 'N', sort: 1, defult: '' },
    { label: '借讀修課學年度', width: '', prop: '借讀修課學年度', hidden: 'N', sort: 2, defult: '' },
    { label: '借讀修課學期', width: '', prop: '借讀修課學期', hidden: 'N', sort: 2, defult: '' },
    { label: '借讀校課程代碼', width: '', prop: '借讀校課程代碼', hidden: 'N', sort: 3, defult: '' },
    { label: '借讀校科目名稱', width: '', prop: '借讀校科目名稱', hidden: 'N', sort: 4, defult: '' },
    { label: '借讀校開課年級', width: '', prop: '借讀校開課年級', hidden: 'N', sort: 5, defult: '' },
    { label: '借讀校修課節數', width: '', prop: '借讀校修課節數', hidden: 'N', sort: 6, defult: '' },
    { label: '成果簡述', width: '', prop: '成果簡述', hidden: 'N', sort: 7, defult: '' },
  ],
  //修課記錄
  學期成績: [
    { label: '課程代碼', width: '', prop: '課程代碼', hidden: 'N', sort: 1, defult: '' },
    { label: '科目名稱', width: '', prop: '科目名稱', hidden: 'N', sort: 2, defult: '' },
    { label: '開課年級', width: '', prop: '開課年級', hidden: 'N', sort: 3, defult: '' },
    { label: '修課學分', width: '', prop: '修課學分', hidden: 'N', sort: 4, defult: '' },
    { label: '學期學業成績', width: '', prop: '學期學業成績', hidden: 'N', sort: 5, defult: '' },
    { label: '成績及格', width: '', prop: '成績及格', hidden: 'N', sort: 6, defult: '' },
    { label: '補考成績', width: '', prop: '補考成績', hidden: 'N', sort: 7, defult: '' },
    { label: '補考及格', width: '', prop: '補考及格', hidden: 'N', sort: 8, defult: '' },
    { label: '是否採計學分', width: '', prop: '是否採計學分', hidden: 'N', sort: 9, defult: '' },
    { label: '質性文字描述', width: '', prop: '質性文字描述', hidden: 'N', sort: 10, defult: '' },
  ],
  補修成績: [
    { label: '課程代碼', width: '', prop: '課程代碼', hidden: 'N', sort: 1, defult: '' },
    { label: '科目名稱', width: '', prop: '科目名稱', hidden: 'N', sort: 2, defult: '' },
    { label: '開課年級', width: '', prop: '開課年級', hidden: 'N', sort: 3, defult: '' },
    { label: '修課學分', width: '', prop: '修課學分', hidden: 'N', sort: 4, defult: '' },
    { label: '應修課學年度', width: '', prop: '應修課學年度', hidden: 'N', sort: 5, defult: '' },
    { label: '應修課學期', width: '', prop: '應修課學期', hidden: 'N', sort: 6, defult: '' },
    { label: '補修成績', width: '', prop: '補修成績', hidden: 'N', sort: 7, defult: '' },
    { label: '補修及格', width: '', prop: '補修及格', hidden: 'N', sort: 8, defult: '' },
    { label: '補考成績', width: '', prop: '補考成績', hidden: 'N', sort: 9, defult: '' },
    { label: '補考及格', width: '', prop: '補考及格', hidden: 'N', sort: 10, defult: '' },
    { label: '是否採計學分', width: '', prop: '是否採計學分', hidden: 'N', sort: 11, defult: '' },
    { label: '質性文字描述', width: '', prop: '質性文字描述', hidden: 'N', sort: 12, defult: '' },
  ],
  轉學轉科成績: [
    { label: '課程代碼', width: '', prop: '課程代碼', hidden: 'N', sort: 1, defult: '' },
    { label: '科目名稱', width: '', prop: '科目名稱', hidden: 'N', sort: 2, defult: '' },
    { label: '修課學分', width: '', prop: '修課學分', hidden: 'N', sort: 3, defult: '' },
    { label: '對應年級', width: '', prop: '對應年級', hidden: 'N', sort: 4, defult: '' },
    { label: '對應學年度', width: '', prop: '對應學年度', hidden: 'N', sort: 5, defult: '' },
    { label: '對應學期', width: '', prop: '對應學期', hidden: 'N', sort: 9, defult: '' },
    { label: '身分別', width: '', prop: '身分別', hidden: 'N', sort: 6, defult: '' },
    { label: '成績及格', width: '', prop: '成績及格', hidden: 'N', sort: 10, defult: '' },
    { label: '是否採計學分', width: '', prop: '是否採計學分', hidden: 'N', sort: 7, defult: '' },
    { label: '抵免後成績', width: '', prop: '抵免後成績', hidden: 'N', sort: 8, defult: '' },
    { label: '質性文字描述', width: '', prop: '質性文字描述', hidden: 'N', sort: 11, defult: '' },
  ],
  重修成績: [
    { label: '原修課學年度', width: '', prop: '原修課學年度', hidden: 'N', sort: 1, defult: '' },
    { label: '原修課學期', width: '', prop: '原修課學期', hidden: 'N', sort: 2, defult: '' },
    { label: '原修課課程代碼', width: '', prop: '原修課課程代碼', hidden: 'N', sort: 3, defult: '' },
    { label: '原修課科目名稱', width: '', prop: '原修課科目名稱', hidden: 'N', sort: 4, defult: '' },
    { label: '原修課開課年級', width: '', prop: '原修課開課年級', hidden: 'N', sort: 5, defult: '' },
    { label: '原修課修課學分', width: '', prop: '原修課修課學分', hidden: 'N', sort: 6, defult: '' },
    { label: '重修成績', width: '', prop: '重修成績', hidden: 'N', sort: 7, defult: '' },
    { label: '重修及格', width: '', prop: '重修及格', hidden: 'N', sort: 8, defult: '' },
    { label: '質性文字描述', width: '', prop: '質性文字描述', hidden: 'N', sort: 9, defult: '' },
  ],
  重讀成績: [
    { label: '課程代碼', width: '', prop: '課程代碼', hidden: 'N', sort: 1, defult: '' },
    { label: '科目名稱', width: '', prop: '科目名稱', hidden: 'N', sort: 2, defult: '' },
    { label: '開課年級', width: '', prop: '開課年級', hidden: 'N', sort: 3, defult: '' },
    { label: '修課學分', width: '', prop: '修課學分', hidden: 'N', sort: 4, defult: '' },
    { label: '重讀成績', width: '', prop: '重讀成績', hidden: 'N', sort: 5, defult: '' },
    { label: '成績及格', width: '', prop: '成績及格', hidden: 'N', sort: 6, defult: '' },
    { label: '補考成績', width: '', prop: '補考成績', hidden: 'N', sort: 7, defult: '' },
    { label: '補考及格', width: '', prop: '補考及格', hidden: 'N', sort: 8, defult: '' },
    { label: '是否採計學分', width: '', prop: '是否採計學分', hidden: 'N', sort: 9, defult: '' },
    { label: '重讀註記', width: '', prop: '重讀註記', hidden: 'N', sort: 10, defult: '' },
    { label: '質性文字描述', width: '', prop: '質性文字描述', hidden: 'N', sort: 11, defult: '' },
  ],
  進修部學期成績: [
    { label: '課程代碼', width: '', prop: '課程代碼', hidden: 'N', sort: 1, defult: '' },
    { label: '科目名稱', width: '', prop: '科目名稱', hidden: 'N', sort: 2, defult: '' },
    { label: '開課年級', width: '', prop: '開課年級', hidden: 'N', sort: 3, defult: '' },
    { label: '修課節數', width: '', prop: '修課節數', hidden: 'N', sort: 4, defult: '' },
    { label: '學期學業成績', width: '', prop: '學期學業成績', hidden: 'N', sort: 5, defult: '' },
    { label: '成績及格', width: '', prop: '成績及格', hidden: 'N', sort: 6, defult: '' },
    { label: '學年學業成績', width: '', prop: '學年學業成績', hidden: 'N', sort: 7, defult: '' },
    { label: '學年及格', width: '', prop: '學年及格', hidden: 'N', sort: 8, defult: '' },
    { label: '是否採計學時', width: '', prop: '是否採計學時', hidden: 'N', sort: 9, defult: '' },
    { label: '質性文字描述', width: '', prop: '質性文字描述', hidden: 'N', sort: 10, defult: '' },
  ],
  進修部補考成績: [
    { label: '課程代碼', width: '', prop: '課程代碼', hidden: 'N', sort: 1, defult: '' },
    { label: '科目名稱', width: '', prop: '科目名稱', hidden: 'N', sort: 2, defult: '' },
    { label: '開課年級', width: '', prop: '開課年級', hidden: 'N', sort: 3, defult: '' },
    { label: '第一學期開設修課節數', width: '', prop: '第一學期開設修課節數', hidden: 'N', sort: 4, defult: '' },
    { label: '第二學期開設修課節數', width: '', prop: '第二學期開設修課節數', hidden: 'N', sort: 5, defult: '' },
    { label: '第一次補考成績', width: '', prop: '第一次補考成績', hidden: 'N', sort: 6, defult: '' },
    { label: '第一次及格', width: '', prop: '第一次及格', hidden: 'N', sort: 7, defult: '' },
    { label: '第二次補考成績', width: '', prop: '第二次補考成績', hidden: 'N', sort: 8, defult: '' },
    { label: '第二次及格', width: '', prop: '第二次及格', hidden: 'N', sort: 9, defult: '' },
  ],
  進修部轉學轉科成績: [
    { label: '課程代碼', width: '', prop: '課程代碼', hidden: 'N', sort: 1, defult: '' },
    { label: '科目名稱', width: '', prop: '科目名稱', hidden: 'N', sort: 2, defult: '' },
    { label: '對應年級', width: '', prop: '對應年級', hidden: 'N', sort: 3, defult: '' },
    { label: '對應學年度', width: '', prop: '對應學年度', hidden: 'N', sort: 4, defult: '' },
    { label: '對應學期', width: '', prop: '對應學期', hidden: 'N', sort: 5, defult: '' },
    { label: '身分別', width: '', prop: '身分別', hidden: 'N', sort: 6, defult: '' },
    { label: '抵免後成績', width: '', prop: '抵免後成績', hidden: 'N', sort: 7, defult: '' },
    { label: '成績及格', width: '', prop: '成績及格', hidden: 'N', sort: 8, defult: '' },
    { label: '是否採計學時', width: '', prop: '是否採計學時', hidden: 'N', sort: 9, defult: '' },
    { label: '修課節數', width: '', prop: '修課節數', hidden: 'N', sort: 10, defult: '' },
    { label: '質性文字描述', width: '', prop: '質性文字描述', hidden: 'N', sort: 11, defult: '' },
  ],
}


export default structure